version: "3.8"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: carsgo
      MYSQL_USER: daniel
      MYSQL_PASSWORD: daniel03
      MYSQL_ROOT_PASSWORD: daniel03
    volumes:
      - ./mysql/data:/home
      - ./mysql/init_data:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306


  flask:
    build: ./flask
    container_name: flask
    links:
      - mysql
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
      - DB_NAME=mysql
    expose:
      - 8080
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "uwsgi", "app.ini"]
          
          
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while:;do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./cerbot/conf:/etc/letsencrypt
        - ./cerbot/www:/var/www/cerbot


  cerbot:
      image: certbot/cerbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      volumes:
          - ./cerbot/conf:/etc/letsencrypt
          - ./cerbot/www:/var/www/cerbot

